// vuejs/src/App.vue
<template>
  <div id="app">
    <div class="container">
      <h1>{{ title }}</h1>
      <p>{{ message }}</p>
      <button @click="fetchData" :disabled="loading">
        {{ loading ? 'Loading...' : 'Fetch Data' }}
      </button>
      <pre v-if="data">{{ JSON.stringify(data, null, 2) }}</pre>
    </div>
  </div>
</template>

<script>
export default {
  name: 'App',
  data() {
    return {
      title: 'Vue.js Docker App',
      message: 'Welcome to Vue.js with Docker!',
      data: null,
      loading: false
    }
  },
  methods: {
    async fetchData() {
      this.loading = true;
      try {
        const response = await fetch('/api/info');
        this.data = await response.json();
      } catch (error) {
        console.error('Error:', error);
      }
      this.loading = false;
    }
  }
}
</script>

<style>
.container {
  padding: 20px;
  text-align: center;
}
button {
  padding: 10px 20px;
  font-size: 16px;
  cursor: pointer;
}
</style>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  template: `
    <div class="container">
      <h1>{{ title }}</h1>
      <p>{{ message }}</p>
      <button (click)="fetchData()">Fetch Data</button>
      <div *ngIf="data">
        <pre>{{ data | json }}</pre>
      </div>
    </div>
  `,
  styles: [`
    .container {
      padding: 20px;
      text-align: center;
    }
  `]
})
export class AppComponent {
  title = 'Angular Docker App';
  message = 'Welcome to Angular with Docker!';
  data: any;

  constructor(private http: HttpClient) {}

  fetchData() {
    this.http.get('/api/info').subscribe(
      response => this.data = response,
      error => console.error('Error:', error)
    );
  }
}
